_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
dataset:
    value:
        input_path: ./data/TinyStories-train.txt
        merges_out: ./cs336_basics/dataset/merges_m4.txt
        special_tokens:
            - <|endoftext|>
        train_path: ./cs336_basics/dataset/train_m4.bin
        val_path: ./cs336_basics/dataset/val_m4.bin
        vocab_out: ./cs336_basics/dataset/vocab_m4.json
model:
    value:
        context_length: 256
        d_ff: 1344
        d_model: 512
        num_heads: 16
        num_layers: 4
        rope_theta: 10000
        vocab_size: 10000
optimizer:
    value:
        cosine_iters: 50000
        learning_rate_max: "2e-4"
        learning_rate_min: "1e-5"
        max_l2_norm: 0.2
        warmup_iters: 5000
        weight_decay: 0.001
training:
    value:
        batch_size: 64
        checkpoint_path: ./cs336_basics/checkpoints/m4_model_v2.pt
        device: auto
        log_every: 500
        max_iters: 50000
        val_every: 500
        wandb: true
        wandb_project: cs336_A1
